### ISSUE TITLE
IPv6 ip_end is wrong when prefix is received from an IPv4 neighbor

### ISSUE THREAD

**Issue by crami** [dpiekacz/gixlg#5]
diff --git a/exabgp/collector.py b/exabgp/collector.py
index e848009..152c844 100755
--- a/exabgp/collector.py
+++ b/exabgp/collector.py
@@ -245,6 +253,11 @@ def Collector_Worker():
                             prefix["subnet"][i] = int(route[x + 1:])
                             prefix["ip_start"][i] = IP2int(route[:x])
-                            if "." in prefix["route"][i]:
-                                prefix["ip_type"] = 4
-                            else:
-                                prefix["ip_type"] = 6
  +
                           if prefix["ip_type"] == 4:
                               prefix["ip_end"][i] = prefix["ip_start"][i] + (2 *\* (32 - prefix["subnet"][i])) - 1
                           else:

**Comment by dpiekacz** [comment]
Thank you for reporting the issue and the fix. I have updated the code on my internal repo and will test the web interface and graphing modules against any side effects. Currently I have limited access to the Internet, so I will push the updated code to github asap.
