### ISSUE TITLE
members table does not get updated

### ISSUE THREAD

**Issue by crami** [dpiekacz/gixlg#6]
Hi Daniel

Since a long time the member table does not get updated, probably since you introduced the delayed updates. I looked at the code an all seams fine. Do you have any Idea where to start debugging?

Regards

  Matthias

**Comment by dpiekacz** [comment]
As the first thing I would suspect that the "Stats_Worker" thread raises an exception. Please enable debugging and look for entries which start from "GIXLG: stats / ...". Almost all except blocks end with pass, so the process won't crash. but all should be logged.

**Comment by tomicke** [comment]
I have also noticed the issue with member table not being updated and i get the following log entries when running debug.

INFO:root:GIXLG: collector / unknown ExaBGP update
INFO:root:GIXLG: stats / update
INFO:root:GIXLG: stats / update
INFO:root:GIXLG: stats / update
INFO:root:GIXLG: stats / update
INFO:root:GIXLG: stats / update
INFO:root:GIXLG: collector queue empty

And it keeps repeating in the logfile. It seems the prefix information is added to the database.
